# Introduction to numpy

In this module we are going to learn to handle datasets, creating , reading from external files , modifying , summarising and visualising  in python with  packages numpy , pandas and seaborn .  this first video focuses on pacakge numpy . Through numpy we will learn to create and handle arrays. Functions that we'll learn here will serve a major purpose

* They will set background for handling columns in our datasets when we eventually move to pandas dataframes


In this section we are going to look at following aspect of numpy arrays
    
    a. creating nd arrays
    
	b. subsetting with indices and conditions
    
    c. comparison with np and math functions [np.sqrt , log etc ], special numpy functions  

Lets get started with creating  two dimensional arrays . Technically you can create arrays with more than two dimensions, but we dont need them for the purpose of this course or most of the machine learning algorithms even the ones which are not covered in the course


In [1]:
import numpy as np

In [2]:
b = np.array([[3,20,99],[-13,4.5,26],[0,-1,20],[5,78,-19]])   
b

array([[  3. ,  20. ,  99. ],
       [-13. ,   4.5,  26. ],
       [  0. ,  -1. ,  20. ],
       [  5. ,  78. , -19. ]])

b here is a 2 dimensional array , you can quickly determine size of each dimension by looking at shape attribute of an array 

In [3]:
b.shape

(4, 3)

dimension in numpy arrays are refered as axis, 2d arrays have two axis , labeled as 0 and 1. 

Since there are two dimension here we'll need to pass double indices while accessing them. counting along both the axes starts with 0

if we want to extract value -1 from the array created above , we will need to access it with its indices across both the axes. which are 2 and 1

In [4]:
b[2,1]

-1.0

For better understanding we can consider the first index to be index of the list where the element is , and second to be its index within that list. Indexing and slicing here works just as it worked for lists , just in two dimensions. lets look at few more examples

In [5]:
print(b)
b[:,1]

[[  3.   20.   99. ]
 [-13.    4.5  26. ]
 [  0.   -1.   20. ]
 [  5.   78.  -19. ]]


array([ 20. ,   4.5,  -1. ,  78. ])

as you can see , this simply gives us 2nd element from all the lists, and this gives us all the elements from the 2nd ist

In [6]:
b[1,:]

array([-13. ,   4.5,  26. ])

by default you can access all the elements of a single list in a 2d array by providing a single index as well

In [7]:
b[1]

array([-13. ,   4.5,  26. ])

you can pass lists of indices as well to access multiple elements of a 2d array

In [8]:
b[[0,1,1],[1,2,1]]

array([ 20. ,  26. ,   4.5])

here elements will come from pairing of indices , (0,1) , (1,2) and (1,1)

you can use thin index access for modification as well

In [9]:
print(b)
b[[0,1,1],[1,2,1]]=[-10,-20,-30]
print(b)

[[  3.   20.   99. ]
 [-13.    4.5  26. ]
 [  0.   -1.   20. ]
 [  5.   78.  -19. ]]
[[  3. -10.  99.]
 [-13. -30. -20.]
 [  0.  -1.  20.]
 [  5.  78. -19.]]


you can see that corresponding elements are now changed to new values 

you subset an array on the basis of condition also

In [10]:
b[b>0]

array([  3.,  99.,  20.,   5.,  78.])

In [11]:
print(b)
b[:,b[2]>=0]

[[  3. -10.  99.]
 [-13. -30. -20.]
 [  0.  -1.  20.]
 [  5.  78. -19.]]


array([[  3.,  99.],
       [-13., -20.],
       [  0.,  20.],
       [  5., -19.]])

keep in mind that applied condition should match in dimension size to which it is being applied if we want to apply it across a single dimension

In [12]:
b[2]>=0

array([ True, False,  True], dtype=bool)

this condition gets applied across all the lists and they have dimension size as 3 

if we wanted to apply the condition to first element of each list and then wanted to keep all corresponding elements across lists, we will have to write it like this 

In [13]:
b[:,2]>=0

array([ True, False,  True, False], dtype=bool)

In [14]:
print(b)
b[b[:,2]>=0,:]

[[  3. -10.  99.]
 [-13. -30. -20.]
 [  0.  -1.  20.]
 [  5.  78. -19.]]


array([[  3., -10.,  99.],
       [  0.,  -1.,  20.]])

If we wanted to apply functions which work on multiple values or across a full dimension instead of single value , we will need to use numpy function instead of math package function because they work on scalars of single values . Lets try using them anyway , lets say we wanted to replace the entire 2nd list ( index =1 ) with its aboslute values.

In [15]:
import math as m


In [16]:
b[1]=m.fabs(b[1])

TypeError: only length-1 arrays can be converted to Python scalars

In [17]:
print(b)
b[1]=np.abs(b[1])
print(b)

[[  3. -10.  99.]
 [-13. -30. -20.]
 [  0.  -1.  20.]
 [  5.  78. -19.]]
[[  3. -10.  99.]
 [ 13.  30.  20.]
 [  0.  -1.  20.]
 [  5.  78. -19.]]


there are multiple such functions available in numpy you can write np. and then hit tab to show you the list of such functions 

In [18]:
print(b)
b[1]=np.sqrt(b[1])
print(b)

[[  3. -10.  99.]
 [ 13.  30.  20.]
 [  0.  -1.  20.]
 [  5.  78. -19.]]
[[  3.         -10.          99.        ]
 [  3.60555128   5.47722558   4.47213595]
 [  0.          -1.          20.        ]
 [  5.          78.         -19.        ]]


these functions can work across dimensions or multiple values at once 

to better understand idea of axis labels 0 and 1 , we will look at a function which collapses the array 

In [19]:
np.sum(b)

188.55491280551524

this simply sums the entire array , now lets instead of this we wanted sum across axis 0 

In [20]:
print(b)
np.sum(b,axis=0)

[[  3.         -10.          99.        ]
 [  3.60555128   5.47722558   4.47213595]
 [  0.          -1.          20.        ]
 [  5.          78.         -19.        ]]


array([  11.60555128,   72.47722558,  104.47213595])

axis 0 here corresponds to elements across the lists , axis=1 corresponds to with in the list elements 

In [21]:

print(b)
np.sum(b,axis=1)

[[  3.         -10.          99.        ]
 [  3.60555128   5.47722558   4.47213595]
 [  0.          -1.          20.        ]
 [  5.          78.         -19.        ]]


array([ 92.        ,  13.55491281,  19.        ,  64.        ])

As note keep in mind that when we start to work with pandas dataframes which are in a way 2d numpy arrays , each list will correspond to a column in the data. In that respect you can say axis=0 represent rows and axis=1 represent columns of a data frame

Next we will look at a small subset of numpy functions which are commonly used a lot , rarely used functions of numpy we will learn about as and when we comes across their specific use cases 

These functions help in quickly creating special kind of numpy arrays

In [22]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [23]:
np.arange(2,8)

array([2, 3, 4, 5, 6, 7])

As you can see arange function can be used to create sequence of integers with increment of 1. For creating a more custom sequence we can use linspace

In [24]:
np.linspace(start=2,stop=10,num=15)

array([  2.        ,   2.57142857,   3.14285714,   3.71428571,
         4.28571429,   4.85714286,   5.42857143,   6.        ,
         6.57142857,   7.14285714,   7.71428571,   8.28571429,
         8.85714286,   9.42857143,  10.        ])

here argument num essentially represent number of elements in sequence , elements in sequence are natuarlly equally spaced .

you can also create new arrays by randomly sampling an original array, or simply creating an array with random numbers using random package within numpy

In [25]:
np.random.randint(high=10,low=1,size=(2,3))

array([[6, 6, 6],
       [5, 5, 6]])

In [26]:
np.random.randint(high=10,low=1,size=(2,))

array([8, 7])

In [27]:
np.random.random(size=(3,4))

array([[ 0.38817439,  0.09900971,  0.52085133,  0.62444997],
       [ 0.78408884,  0.89925316,  0.42730569,  0.14417496],
       [ 0.23456522,  0.14269301,  0.0588833 ,  0.29127285]])

In [28]:
x=np.arange(10)

In [29]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.random.choice(x,6)

array([5, 0, 4, 6, 7, 8])

In [31]:
np.random.choice(x,6,replace=False)

array([6, 1, 8, 2, 5, 0])

In [32]:
y=np.random.choice(['a','b'],6)
print(y)

['a' 'b' 'b' 'b' 'b' 'b']


In [33]:
y=np.random.choice(['a','b'],1000)


In [34]:
np.unique(y,return_counts=True)

(array(['a', 'b'], 
       dtype='<U1'), array([498, 502]))

by default here both a and b get picked with almost equal probability in the random sample. Although this doesnt mean that individual values are not random , but overall percentage of a and b remains almost same. We can force approx probability structure by using option p

In [35]:
y=np.random.choice(['a','b'],1000,p=[0.8,0.2])

In [36]:
np.unique(y,return_counts=True)

(array(['a', 'b'], 
       dtype='<U1'), array([801, 199]))

Another useful function is for sorting 

In [37]:
x=np.random.randint(high=100,low=12,size=(15,))

In [38]:
x.sort()

In [39]:
x

array([18, 18, 20, 22, 28, 32, 35, 44, 59, 75, 88, 92, 96, 96, 99])

Now lets look at sorting 2darrays 

In [40]:
x=np.random.randint(high=100,low=12,size=(4,6))

In [41]:
x

array([[79, 30, 44, 17, 90, 71],
       [81, 38, 13, 81, 31, 76],
       [43, 45, 91, 92, 62, 45],
       [70, 76, 32, 85, 46, 94]])

if you simply sort it sorts each individual array without mainting any order 

In [42]:
x.sort()

In [43]:
x

array([[17, 30, 44, 71, 79, 90],
       [13, 31, 38, 76, 81, 81],
       [43, 45, 45, 62, 91, 92],
       [32, 46, 70, 76, 85, 94]])

In [44]:
x=np.random.randint(high=100,low=12,size=(4,6))
x

array([[30, 70, 53, 47, 16, 40],
       [85, 43, 71, 81, 78, 35],
       [91, 51, 86, 22, 75, 89],
       [67, 51, 25, 95, 84, 83]])

For maintaining order along either of the axis what we can do is that we can extract indices of the sorted values and reorder original array with , here is what i mean

In [45]:
x[:,2]

array([53, 71, 86, 25])

these are the 3rd elements of all arrays , lets i want to sort my 2darray by these and other values should move with them maintaining correspondence

In [46]:

x[:,2].argsort()

array([3, 0, 1, 2])

what argsort does is that it gives indices of sorted elements , now we can arrange the list along another axes using the result of argsort like this 

In [47]:
x[x[:,2].argsort(),:]

array([[67, 51, 25, 95, 84, 83],
       [30, 70, 53, 47, 16, 40],
       [85, 43, 71, 81, 78, 35],
       [91, 51, 86, 22, 75, 89]])

you can see that correspondence doesnt break here

similar to sort and argsort , another use ful combination at times is max and argmax and its counterparts min and argmin

In [48]:
x=np.random.randint(high=100,low=12,size=(15,))

In [49]:
x

array([35, 53, 74, 82, 61, 43, 21, 84, 71, 84, 94, 73, 87, 32, 95])

In [50]:
x.max()

95

In [51]:
x.argmax()

14

We will stop our discussion on numpy , other numpy related functions which are not as often used will be discussed as and when we come across their use case. In the next section we will start with pandas , the go to package for handling datasets in python. 

# introduction to pandas

In this module we will start with the fabled python package named pandas which has become defacto tool for handling datasets in python. In this section we will look at following aspects of pandas 

1. Manually creating data frames 
2. Reading data from external file
3. peripheral summary of the data
4. subsetting on the basis of rownumber , colnumber 
5. subsetting on the basis of condition 
6. subsetting on the basis of column names

lets import the package first and then we will create dataframes manually

In [52]:
import pandas as pd
import numpy as np

there are two ways to create dataframes from list of values as columns . Lets first create some lists values 

In [53]:
age=np.random.randint(low=16,high=80,size=[20,])
city=np.random.choice(['Mumbai','Delhi','Chennai','Kolkata'],20)
default=np.random.choice([0,1],20)

we can zip these to convert them to single list of tuples , each tuple in that list will correspond to a row in the dataframe

In [54]:
mydata=list(zip(age,city,default))

In [55]:
mydata

[(64, 'Mumbai', 1),
 (67, 'Chennai', 0),
 (26, 'Mumbai', 1),
 (50, 'Kolkata', 0),
 (23, 'Kolkata', 0),
 (71, 'Chennai', 0),
 (34, 'Mumbai', 0),
 (44, 'Mumbai', 0),
 (56, 'Kolkata', 1),
 (30, 'Mumbai', 0),
 (24, 'Chennai', 1),
 (56, 'Mumbai', 1),
 (55, 'Chennai', 1),
 (67, 'Mumbai', 0),
 (51, 'Chennai', 1),
 (24, 'Mumbai', 1),
 (62, 'Delhi', 0),
 (63, 'Delhi', 1),
 (41, 'Delhi', 1),
 (21, 'Kolkata', 0)]

In [56]:
df=pd.DataFrame(data=mydata,columns=['age','city','default'])

In [57]:
df

age     city  default
0    64   Mumbai        1
1    67  Chennai        0
2    26   Mumbai        1
3    50  Kolkata        0
4    23  Kolkata        0
5    71  Chennai        0
6    34   Mumbai        0
7    44   Mumbai        0
8    56  Kolkata        1
9    30   Mumbai        0
10   24  Chennai        1
11   56   Mumbai        1
12   55  Chennai        1
13   67   Mumbai        0
14   51  Chennai        1
15   24   Mumbai        1
16   62    Delhi        0
17   63    Delhi        1
18   41    Delhi        1
19   21  Kolkata        0

Another way is to put them in a dictionary , you will not need to supply column names separately in this case 

In [58]:
df=pd.DataFrame({'age':age,'city':city,'default':default})

In [59]:
df

age     city  default
0    64   Mumbai        1
1    67  Chennai        0
2    26   Mumbai        1
3    50  Kolkata        0
4    23  Kolkata        0
5    71  Chennai        0
6    34   Mumbai        0
7    44   Mumbai        0
8    56  Kolkata        1
9    30   Mumbai        0
10   24  Chennai        1
11   56   Mumbai        1
12   55  Chennai        1
13   67   Mumbai        0
14   51  Chennai        1
15   24   Mumbai        1
16   62    Delhi        0
17   63    Delhi        1
18   41    Delhi        1
19   21  Kolkata        0

just the process of creating them is different , there is no difference in properties of end result

we can read data from external file very easily using function read_csv from pandas

In [60]:
file=r'/Users/lalitsachan/Dropbox/PDS V3/Data/loans data.csv'

here r is added at the begning of the path to file to make it a raw string , so that its treated as path as is and any special oocurences are not interpreted as their special meaning by python. For example \n means newline , which will be ignored when we add r at the beginning of the string 

In [61]:
ld=pd.read_csv(file)

to view first few obs of the data we can write 

In [62]:
ld.head()

ID Amount.Requested Amount.Funded.By.Investors Interest.Rate  \
0  81174.0            20000                      20000         8.90%   
1  99592.0            19200                      19200        12.12%   
2  80059.0            35000                      35000        21.98%   
3  15825.0            10000                       9975         9.99%   
4  33182.0            12000                      12000        11.71%   

  Loan.Length        Loan.Purpose Debt.To.Income.Ratio State Home.Ownership  \
0   36 months  debt_consolidation               14.90%    SC       MORTGAGE   
1   36 months  debt_consolidation               28.36%    TX       MORTGAGE   
2   60 months  debt_consolidation               23.81%    CA       MORTGAGE   
3   36 months  debt_consolidation               14.30%    KS       MORTGAGE   
4   36 months         credit_card               18.78%    NJ           RENT   

   Monthly.Income FICO.Range Open.CREDIT.Lines Revolving.CREDIT.Balance  \
0         6541.67    735-739                14                    14272   
1         4583.33    715-719                12                    11140   
2        11500.00    690-694                14                    21977   
3         3833.33    695-699                10                     9346   
4         3195.00    695-699                11                    14469   

   Inquiries.in.the.Last.6.Months Employment.Length  
0                             2.0          < 1 year  
1                             1.0           2 years  
2                             1.0           2 years  
3                             0.0           5 years  
4                             0.0           9 years

to get column names we can look attribute column of the data`

In [63]:
ld.columns

Index(['ID', 'Amount.Requested', 'Amount.Funded.By.Investors', 'Interest.Rate',
       'Loan.Length', 'Loan.Purpose', 'Debt.To.Income.Ratio', 'State',
       'Home.Ownership', 'Monthly.Income', 'FICO.Range', 'Open.CREDIT.Lines',
       'Revolving.CREDIT.Balance', 'Inquiries.in.the.Last.6.Months',
       'Employment.Length'],
      dtype='object')

to see type of these columns we can use attribute dtypes

In [64]:
ld.dtypes

ID                                float64
Amount.Requested                   object
Amount.Funded.By.Investors         object
Interest.Rate                      object
Loan.Length                        object
Loan.Purpose                       object
Debt.To.Income.Ratio               object
State                              object
Home.Ownership                     object
Monthly.Income                    float64
FICO.Range                         object
Open.CREDIT.Lines                  object
Revolving.CREDIT.Balance           object
Inquiries.in.the.Last.6.Months    float64
Employment.Length                  object
dtype: object

flost64 here correponds to numeric values and object corresponds to categorical columns

to know how many rows and columns are their in the data we can use attribute shape

In [65]:
ld.shape

(2500, 15)

this tells us that the data has 2500 rows/observations and 15 columns in it

now lets subset this data on the basis of row and column numbers , keep in mind that count start with 0 for both 

In [66]:
ld1=ld.iloc[3:7,1:5]
ld1

Amount.Requested Amount.Funded.By.Investors Interest.Rate Loan.Length
3            10000                       9975         9.99%   36 months
4            12000                      12000        11.71%   36 months
5             6000                       6000        15.31%   36 months
6            10000                      10000         7.90%   36 months

iloc here correponds to subsetting by position , to understand this better lets try to further subset this data

In [67]:
ld1.iloc[2:4,1:3]

Amount.Funded.By.Investors Interest.Rate
5                       6000        15.31%
6                      10000         7.90%

as you can see here the position is relative to current data , not the original one

Generally however we do not subset data by positions , we subset by either conditions or column names , if we are subsetting just on the basis of conditions or just column names we can directly pass those in square brackets

In [68]:
ld[(ld['Home.Ownership']=='MORTGAGE') & (ld['Monthly.Income']>5000)]

ID Amount.Requested Amount.Funded.By.Investors Interest.Rate  \
0      81174.0            20000                      20000         8.90%   
2      80059.0            35000                      35000        21.98%   
7      22090.0            33500                      33450        17.14%   
12     41200.0            28000                      27975        21.67%   
20     86099.0            22000                      21975        21.98%   
21     99483.0            30000                      30000        19.05%   
30     87023.0            23850                      23850        21.00%   
31     46120.0            14000                      14000        12.12%   
32     30756.0            35000                      34975        16.49%   
35     96536.0             8000                       7975         7.90%   
47     34501.0            20000                      19975        23.91%   
58     96613.0            27575                      27575        14.33%   
61     99766.0            30000                      30000        10.16%   
79     61576.0            18550                      18525         7.90%   
80     21993.0             7450                       7450        13.06%   
81     58359.0             3225                       3225         7.62%   
85    103948.0            16000                      15850        11.12%   
91     67629.0            16000                      15925         7.62%   
94    103405.0            10000                       9975        14.96%   
95     53271.0             7000                       7000         6.62%   
96     25380.0             4500                       4500         5.99%   
97      6987.0            12000                      12000        11.14%   
99     88273.0             4800                       4800        18.75%   
104    34122.0            15000                      15000        10.65%   
106    98634.0            20000                      20000         6.03%   
111    64884.0             9000                       9000         6.03%   
114    77151.0            20950                      20950        15.80%   
118    54649.0            14000                      14000         6.03%   
120    74479.0            25000                      25000        19.05%   
123    32008.0            14000                      14000         8.49%   
...        ...              ...                        ...           ...   
2412    9618.0            24000                   21963.64        10.99%   
2413   82216.0            15000                      15000         8.90%   
2414   87554.0            24000                      23950        24.89%   
2422   45453.0            20000                      19975        22.78%   
2429   65776.0            15000                      15000        17.77%   
2440   11723.0            20000                      20000        18.30%   
2441   22659.0            12000                      12000        12.68%   
2444   59011.0            13000                      13000         6.62%   
2446   90560.0            11400                      11375         8.90%   
2447   79820.0            25875                      25875        18.49%   
2453   72356.0            28200                      28150        10.16%   
2454   42253.0            20000                      19925        18.64%   
2455   98954.0            24000                      24000        16.29%   
2460   68406.0            20000                      20000        14.09%   
2462   14044.0             3500                       3500        11.49%   
2468   19492.0             3500                       3500         7.29%   
2469   22132.0            20000                    17724.9        10.74%   
2471   80231.0            19000                      19000         7.90%   
2472   49533.0            17300                      17250        22.45%   
2476   80129.0             4000                       3925        14.09%   
2477   85216.0            17500                      17500  

a single column name can be directly passed

In [69]:
ld['Home.Ownership']

0       MORTGAGE
1       MORTGAGE
2       MORTGAGE
3       MORTGAGE
4           RENT
5            OWN
6           RENT
7       MORTGAGE
8           RENT
9           RENT
10          RENT
11      MORTGAGE
12      MORTGAGE
13          RENT
14          RENT
15          RENT
16          RENT
17          RENT
18          RENT
19      MORTGAGE
20      MORTGAGE
21      MORTGAGE
22          RENT
23          RENT
24      MORTGAGE
25          RENT
26          RENT
27      MORTGAGE
28      MORTGAGE
29      MORTGAGE
          ...   
2470        RENT
2471    MORTGAGE
2472    MORTGAGE
2473    MORTGAGE
2474        RENT
2475        RENT
2476    MORTGAGE
2477    MORTGAGE
2478    MORTGAGE
2479    MORTGAGE
2480        RENT
2481    MORTGAGE
2482    MORTGAGE
2483    MORTGAGE
2484    MORTGAGE
2485    MORTGAGE
2486         OWN
2487        RENT
2488        RENT
2489        RENT
2490        RENT
2491        RENT
2492    MORTGAGE
2493    MORTGAGE
2494    MORTGAGE
2495    MORTGAGE
2496         OWN
2497    MORTGA

however mulitple column names need to be passed as a list 

In [70]:
ld[['Home.Ownership','Monthly.Income']]

Home.Ownership  Monthly.Income
0          MORTGAGE         6541.67
1          MORTGAGE         4583.33
2          MORTGAGE        11500.00
3          MORTGAGE         3833.33
4              RENT         3195.00
5               OWN         4891.67
6              RENT         2916.67
7          MORTGAGE        13863.42
8              RENT         3150.00
9              RENT         5000.00
10             RENT         3575.00
11         MORTGAGE         4250.00
12         MORTGAGE        14166.67
13             RENT         9166.67
14             RENT        11250.00
15             RENT         5416.67
16             RENT         9000.00
17             RENT         4333.33
18             RENT         2733.33
19         MORTGAGE         3750.00
20         MORTGAGE         6666.67
21         MORTGAGE         6250.00
22             RENT         4100.00
23             RENT         6833.33
24         MORTGAGE         4500.00
25             RENT         5416.67
26             RENT         2964.17
27         MORTGAGE         2916.67
28         MORTGAGE         4167.00
29         MORTGAGE         3958.33
...             ...             ...
2470           RENT         6750.00
2471       MORTGAGE         5166.67
2472       MORTGAGE         5500.00
2473       MORTGAGE         3833.00
2474           RENT         8333.33
2475           RENT         4583.33
2476       MORTGAGE         8583.33
2477       MORTGAGE        25000.00
2478       MORTGAGE         5416.67
2479       MORTGAGE         4833.33
2480           RENT         5000.00
2481       MORTGAGE         9250.00
2482       MORTGAGE         7075.50
2483       MORTGAGE         3416.67
2484       MORTGAGE         6666.67
2485       MORTGAGE         7083.33
2486            OWN         2464.37
2487           RENT         8000.00
2488           RENT         3833.33
2489           RENT         5166.67
2490           RENT         4500.00
2491           RENT         3983.33
2492       MORTGAGE         5166.67
2493       MORTGAGE         7083.33
2494       MORTGAGE         6666.67
2495       MORTGAGE         9250.00
2496            OWN         8903.25
2497       MORTGAGE         2166.67
2498           RENT         3500.00
2499           RENT         3875.00

[2500 rows x 2 columns]

when using both condition and column names we need to use .loc with dataframe name

In [71]:
ld.loc[(ld['Home.Ownership']=='MORTGAGE') & (ld['Monthly.Income']>5000),['Home.Ownership','Monthly.Income']]

Home.Ownership  Monthly.Income
0          MORTGAGE         6541.67
2          MORTGAGE        11500.00
7          MORTGAGE        13863.42
12         MORTGAGE        14166.67
20         MORTGAGE         6666.67
21         MORTGAGE         6250.00
30         MORTGAGE         5833.33
31         MORTGAGE        10583.33
32         MORTGAGE        10416.67
35         MORTGAGE         5583.33
47         MORTGAGE        11250.00
58         MORTGAGE         5166.67
61         MORTGAGE         8000.00
79         MORTGAGE         5416.67
80         MORTGAGE         5883.33
81         MORTGAGE         5833.33
85         MORTGAGE         6666.67
91         MORTGAGE         6000.00
94         MORTGAGE         5250.00
95         MORTGAGE        10000.00
96         MORTGAGE        10000.00
97         MORTGAGE        12500.00
99         MORTGAGE         5833.33
104        MORTGAGE         7083.33
106        MORTGAGE        14583.33
111        MORTGAGE         9583.33
114        MORTGAGE        12916.67
118        MORTGAGE         6000.00
120        MORTGAGE         6250.00
123        MORTGAGE         9000.00
...             ...             ...
2412       MORTGAGE        12500.00
2413       MORTGAGE         9583.33
2414       MORTGAGE        10737.50
2422       MORTGAGE         5666.67
2429       MORTGAGE         6000.00
2440       MORTGAGE         5833.00
2441       MORTGAGE         9750.00
2444       MORTGAGE        11666.67
2446       MORTGAGE         5641.67
2447       MORTGAGE         6000.00
2453       MORTGAGE         5900.00
2454       MORTGAGE         6250.00
2455       MORTGAGE         5577.26
2460       MORTGAGE        19583.33
2462       MORTGAGE         9166.67
2468       MORTGAGE         6333.00
2469       MORTGAGE         6125.00
2471       MORTGAGE         5166.67
2472       MORTGAGE         5500.00
2476       MORTGAGE         8583.33
2477       MORTGAGE        25000.00
2478       MORTGAGE         5416.67
2481       MORTGAGE         9250.00
2482       MORTGAGE         7075.50
2484       MORTGAGE         6666.67
2485       MORTGAGE         7083.33
2492       MORTGAGE         5166.67
2493       MORTGAGE         7083.33
2494       MORTGAGE         6666.67
2495       MORTGAGE         9250.00

[686 rows x 2 columns]

do keep in mind that the accessed elements in these ways can also be modified by equating them to appropriate replacement to them

in order to negate a condition or drop rows on the basis of a conditon , we just need to add a ~ symbol in front of the condition 

In [72]:
ld[~((ld['Home.Ownership']=='MORTGAGE') & (ld['Monthly.Income']>5000))]

ID Amount.Requested Amount.Funded.By.Investors Interest.Rate  \
1      99592.0            19200                      19200        12.12%   
3      15825.0            10000                       9975         9.99%   
4      33182.0            12000                      12000        11.71%   
5      62403.0             6000                       6000        15.31%   
6      48808.0            10000                      10000         7.90%   
8      76404.0            14675                      14675        14.33%   
9      15867.0                .                       7000         6.91%   
10     94971.0             2000                       2000        19.72%   
11     36911.0            10625                      10625        14.27%   
13     83869.0            35000                      34950         8.90%   
14     53853.0             9600                       9600         7.62%   
15     21399.0            25000                      24975        15.65%   
16     62127.0            10000                      10000        12.12%   
17     23446.0            14000                   13900.25        10.37%   
18     44987.0            10000                      10000         9.76%   
19     17977.0             5200                       5175         9.99%   
22     28798.0             6500                       6500        17.99%   
23     24168.0            17400                      17400        11.99%   
24     10356.0             4000                       4000        16.82%   
25     46027.0             7200                       7200         7.90%   
26      2238.0             8000                       8000        14.42%   
27     65278.0             8000                       8000        15.31%   
28      4227.0             3000                          .         8.59%   
29     50182.0            14500                      14500         7.90%   
33     94582.0            16000                      16000        15.80%   
34       457.0            17350                    7019.25        13.55%   
36     39591.0             7200                       7200         7.90%   
37     78862.0            20125                      20125         7.62%   
38     54619.0            12000                      11875         8.90%   
39    101798.0                .                       1850        12.49%   
...        ...              ...                        ...           ...   
2450   26867.0            14000                      12800        14.79%   
2451    3508.0             2000                       2000        16.00%   
2452   52759.0            25000                      25000         7.90%   
2456   98510.0            21850                      21850        17.27%   
2457    5821.0            20000                      19850        13.22%   
2458    8692.0            16000                      15875        13.85%   
2459   94839.0            10000                      10000        11.14%   
2461   86117.0             1000                       1000         7.90%   
2463   43056.0            15000                      15000         7.90%   
2464   45519.0            19000                      19000        13.67%   
2465   45424.0            12000                      11950         6.03%   
2466   92038.0            22750                      22750        22.47%   
2467   21716.0             9800                     9747.5         7.29%   
2470   84265.0            20000                      20000        22.95%   
2473  102514.0             7000                     711.54        15.13%   
2474   78618.0             7200                       7200        18.75%   
2475   86953.0            10000                      10000        14.09%   
2479   91245.0            16200                      16200        15.80%   
2480   53041.0            10000                      10000         6.03%   
2483   68628.0                .                      15875        14.33%   
2486   45836.0             7000                       7000  

in order to drop columns on the basis of names we can make use of the inbuilt drop function

In [73]:
ld.drop(['Home.Ownership','Monthly.Income'],axis=1)

ID Amount.Requested Amount.Funded.By.Investors Interest.Rate  \
0      81174.0            20000                      20000         8.90%   
1      99592.0            19200                      19200        12.12%   
2      80059.0            35000                      35000        21.98%   
3      15825.0            10000                       9975         9.99%   
4      33182.0            12000                      12000        11.71%   
5      62403.0             6000                       6000        15.31%   
6      48808.0            10000                      10000         7.90%   
7      22090.0            33500                      33450        17.14%   
8      76404.0            14675                      14675        14.33%   
9      15867.0                .                       7000         6.91%   
10     94971.0             2000                       2000        19.72%   
11     36911.0            10625                      10625        14.27%   
12     41200.0            28000                      27975        21.67%   
13     83869.0            35000                      34950         8.90%   
14     53853.0             9600                       9600         7.62%   
15     21399.0            25000                      24975        15.65%   
16     62127.0            10000                      10000        12.12%   
17     23446.0            14000                   13900.25        10.37%   
18     44987.0            10000                      10000         9.76%   
19     17977.0             5200                       5175         9.99%   
20     86099.0            22000                      21975        21.98%   
21     99483.0            30000                      30000        19.05%   
22     28798.0             6500                       6500        17.99%   
23     24168.0            17400                      17400        11.99%   
24     10356.0             4000                       4000        16.82%   
25     46027.0             7200                       7200         7.90%   
26      2238.0             8000                       8000        14.42%   
27     65278.0             8000                       8000        15.31%   
28      4227.0             3000                          .         8.59%   
29     50182.0            14500                      14500         7.90%   
...        ...              ...                        ...           ...   
2470   84265.0            20000                      20000        22.95%   
2471   80231.0            19000                      19000         7.90%   
2472   49533.0            17300                      17250        22.45%   
2473  102514.0             7000                     711.54        15.13%   
2474   78618.0             7200                       7200        18.75%   
2475   86953.0            10000                      10000        14.09%   
2476   80129.0             4000                       3925        14.09%   
2477   85216.0            17500                      17500         8.90%   
2478   38247.0            20000                      20000        11.71%   
2479   91245.0            16200                      16200        15.80%   
2480   53041.0            10000                      10000         6.03%   
2481   63051.0            27000                      27000         6.62%   
2482   14446.0             4500                       4475         7.51%   
2483   68628.0                .                      15875        14.33%   
2484   98758.0            15000                      15000        10.16%   
2485   13070.0            25000                      24950        10.75%   
2486   45836.0             7000                       7000        17.27%   
2487   52330.0            15000                      15000        19.99%   
2488   48243.0            17000                      17000        15.81%   
2489   63256.0            19075                      19075        18.75%   
2490   42124.0            10000                      10000  

if you scroll through the output you will find that those columns are no more in the data, this however doesnt modify the original data , these columns are still present in the data

In [74]:
ld.columns

Index(['ID', 'Amount.Requested', 'Amount.Funded.By.Investors', 'Interest.Rate',
       'Loan.Length', 'Loan.Purpose', 'Debt.To.Income.Ratio', 'State',
       'Home.Ownership', 'Monthly.Income', 'FICO.Range', 'Open.CREDIT.Lines',
       'Revolving.CREDIT.Balance', 'Inquiries.in.the.Last.6.Months',
       'Employment.Length'],
      dtype='object')

you can equate the output to original data name in order to change it , like this 

In [75]:
ld=ld.drop(['Home.Ownership','Monthly.Income'],axis=1)

In [76]:
ld.columns

Index(['ID', 'Amount.Requested', 'Amount.Funded.By.Investors', 'Interest.Rate',
       'Loan.Length', 'Loan.Purpose', 'Debt.To.Income.Ratio', 'State',
       'FICO.Range', 'Open.CREDIT.Lines', 'Revolving.CREDIT.Balance',
       'Inquiries.in.the.Last.6.Months', 'Employment.Length'],
      dtype='object')

or you can make use of the inplace option in the drop function to change the data inplace 

In [77]:
ld.drop(['Debt.To.Income.Ratio', 'State'],axis=1,inplace=True)

this changes the data inplace 

In [78]:
ld.columns

Index(['ID', 'Amount.Requested', 'Amount.Funded.By.Investors', 'Interest.Rate',
       'Loan.Length', 'Loan.Purpose', 'FICO.Range', 'Open.CREDIT.Lines',
       'Revolving.CREDIT.Balance', 'Inquiries.in.the.Last.6.Months',
       'Employment.Length'],
      dtype='object')

notice that those columns are not there in the data inmore , one more thing that you need to be careful with here is that when using inplace=True option, function drop doesnt output anything so dont equate it to original data. if you do original data will end becoming a None type object

another way to delete a column is to use keyword del , the same one which we used in context of dictionary 

In [79]:
del ld['Employment.Length']

In [80]:
ld.columns

Index(['ID', 'Amount.Requested', 'Amount.Funded.By.Investors', 'Interest.Rate',
       'Loan.Length', 'Loan.Purpose', 'FICO.Range', 'Open.CREDIT.Lines',
       'Revolving.CREDIT.Balance', 'Inquiries.in.the.Last.6.Months'],
      dtype='object')

We will stop our dicsusion on pandas dataframe in this section. In the next section , we will see how to add new columns , and modify existing columns in the data. We will also see how to check , count and impute missing value in the data. 

# Modifying data with pandas

 in this particular section we will continue with pandas and further learn about how to modify dataframes using pandas , we'll be using a simulated data for the same as all data prep opportunities might not be present in one single dataset from real world . However the techniques that we'll learn here will be usefull individually in various datasets that you will come across in the course. We'll be using these techniques to prepare our datasets in the machine learning modules of this course. In terms of specific techniques that we will go through in this section, we'll learn 

1. changing variable types 
2. Adding/modifying variables with algebraic operations
3. Adding/modifying variables based on conditions
4. handling missing values 
5. creating flag variables 
6. Creating multiple columns from a variable with separating at a delimiter

lets start with simulating a dataset which will give us opprtunity to try out all these techniques

In [81]:
import numpy as np
import pandas as pd

In [82]:
age=np.random.choice([15,20,30,45,12,'10',15,'34',7,'missing'],50)

fico=np.random.choice(['100-150','150-200','200-250','250-300'],50)

city=np.random.choice(['Mumbai','Delhi','Chennai','Kolkata'],50)
ID=np.arange(50)
rating=np.random.choice(['Excellent','Good','Bad','Pathetic'],50)
balance=np.random.choice([10000,20000,30000,40000,np.nan,50000,60000],50)
children=np.random.randint(high=5,low=0,size=(50,))

In [83]:
mydata=pd.DataFrame({'ID':ID,'age':age,'fico':fico,'city':city,'rating':rating,'balance':balance,'children':children})

In [84]:
mydata

ID      age  balance  children     city     fico     rating
0    0  missing  60000.0         0    Delhi  200-250  Excellent
1    1       34  60000.0         1  Kolkata  150-200        Bad
2    2       30  60000.0         0   Mumbai  100-150       Good
3    3       15      NaN         3  Chennai  250-300       Good
4    4       45      NaN         4   Mumbai  100-150       Good
5    5        7  60000.0         3  Kolkata  250-300        Bad
6    6       45  60000.0         0  Chennai  250-300  Excellent
7    7  missing  20000.0         3    Delhi  100-150   Pathetic
8    8       10  50000.0         0  Chennai  100-150   Pathetic
9    9       15  40000.0         3    Delhi  100-150  Excellent
10  10       12  60000.0         2   Mumbai  250-300       Good
11  11       30  50000.0         3   Mumbai  100-150       Good
12  12       15  50000.0         3  Kolkata  150-200       Good
13  13       12  30000.0         1    Delhi  150-200  Excellent
14  14       45  50000.0         4  Kolkata  100-150   Pathetic
15  15       34  40000.0         3   Mumbai  250-300       Good
16  16  missing  40000.0         0   Mumbai  150-200   Pathetic
17  17       34  40000.0         1  Kolkata  150-200   Pathetic
18  18       15  40000.0         4  Chennai  200-250  Excellent
19  19  missing  40000.0         1  Chennai  100-150   Pathetic
20  20        7      NaN         1    Delhi  100-150   Pathetic
21  21       20  50000.0         1   Mumbai  100-150        Bad
22  22       10  10000.0         4    Delhi  200-250       Good
23  23       15  60000.0         2  Kolkata  100-150  Excellent
24  24       15  20000.0         0  Kolkata  200-250        Bad
25  25       34  60000.0         0    Delhi  200-250        Bad
26  26       20  30000.0         0  Chennai  250-300       Good
27  27       15  30000.0         3    Delhi  250-300       Good
28  28        7      NaN         3   Mumbai  100-150       Good
29  29       12  60000.0         1   Mumbai  150-200   Pathetic
30  30       45  30000.0         4  Chennai  150-200       Good
31  31       12  30000.0         2    Delhi  150-200  Excellent
32  32       12  10000.0         4    Delhi  100-150  Excellent
33  33       20  40000.0         2  Chennai  150-200  Excellent
34  34       20      NaN         1  Kolkata  200-250  Excellent
35  35        7  10000.0         3  Kolkata  200-250        Bad
36  36       10  50000.0         2   Mumbai  150-200  Excellent
37  37        7      NaN         3   Mumbai  200-250       Good
38  38        7  60000.0         2   Mumbai  100-150   Pathetic
39  39       34  50000.0         0   Mumbai  200-250        Bad
40  40       15  10000.0         1    Delhi  100-150        Bad
41  41        7      NaN         0  Chennai  150-200   Pathetic
42  42       15      NaN         4  Kolkata  100-150   Pathetic
43  43       20      NaN         0    Delhi  150-200        Bad
44  44       10  20000.0         3   Mumbai  250-300   Pathetic
45  45       20  20000.0         2   Mumbai  250-300        Bad
46  46       20  10000.0         4  Chennai  100-150  Excellent
47  47       15  10000.0         2   Mumbai  200-250  Excellent
48  48       34  40000.0         4  Kolkata  100-150  Excellent
49  49       20  20000.0         4   Mumbai  200-250        Bad

In [85]:
mydata.dtypes

ID            int64
age          object
balance     float64
children      int64
city         object
fico         object
rating       object
dtype: object

We can see that age here should have been a numeric column, but has comes as character type because of some character values , we can set to be numeric type , the character values which can not be converted to numbers will assinged missing values automatically 

In [86]:
mydata['age']=pd.to_numeric(mydata['age'],errors='coerce')

In [87]:
mydata['age']

0      NaN
1     34.0
2     30.0
3     15.0
4     45.0
5      7.0
6     45.0
7      NaN
8     10.0
9     15.0
10    12.0
11    30.0
12    15.0
13    12.0
14    45.0
15    34.0
16     NaN
17    34.0
18    15.0
19     NaN
20     7.0
21    20.0
22    10.0
23    15.0
24    15.0
25    34.0
26    20.0
27    15.0
28     7.0
29    12.0
30    45.0
31    12.0
32    12.0
33    20.0
34    20.0
35     7.0
36    10.0
37     7.0
38     7.0
39    34.0
40    15.0
41     7.0
42    15.0
43    20.0
44    10.0
45    20.0
46    20.0
47    15.0
48    34.0
49    20.0
Name: age, dtype: float64

Lets look at some algebraic creation modification of columns 

In [88]:
mydata['const_var']=100
mydata['balance_log']=np.log(mydata['balance'])
mydata['age_children_ratio']=mydata['age']/mydata['children']

In [89]:
mydata

ID   age  balance  children     city     fico     rating  const_var  \
0    0   NaN  60000.0         0    Delhi  200-250  Excellent        100   
1    1  34.0  60000.0         1  Kolkata  150-200        Bad        100   
2    2  30.0  60000.0         0   Mumbai  100-150       Good        100   
3    3  15.0      NaN         3  Chennai  250-300       Good        100   
4    4  45.0      NaN         4   Mumbai  100-150       Good        100   
5    5   7.0  60000.0         3  Kolkata  250-300        Bad        100   
6    6  45.0  60000.0         0  Chennai  250-300  Excellent        100   
7    7   NaN  20000.0         3    Delhi  100-150   Pathetic        100   
8    8  10.0  50000.0         0  Chennai  100-150   Pathetic        100   
9    9  15.0  40000.0         3    Delhi  100-150  Excellent        100   
10  10  12.0  60000.0         2   Mumbai  250-300       Good        100   
11  11  30.0  50000.0         3   Mumbai  100-150       Good        100   
12  12  15.0  50000.0         3  Kolkata  150-200       Good        100   
13  13  12.0  30000.0         1    Delhi  150-200  Excellent        100   
14  14  45.0  50000.0         4  Kolkata  100-150   Pathetic        100   
15  15  34.0  40000.0         3   Mumbai  250-300       Good        100   
16  16   NaN  40000.0         0   Mumbai  150-200   Pathetic        100   
17  17  34.0  40000.0         1  Kolkata  150-200   Pathetic        100   
18  18  15.0  40000.0         4  Chennai  200-250  Excellent        100   
19  19   NaN  40000.0         1  Chennai  100-150   Pathetic        100   
20  20   7.0      NaN         1    Delhi  100-150   Pathetic        100   
21  21  20.0  50000.0         1   Mumbai  100-150        Bad        100   
22  22  10.0  10000.0         4    Delhi  200-250       Good        100   
23  23  15.0  60000.0         2  Kolkata  100-150  Excellent        100   
24  24  15.0  20000.0         0  Kolkata  200-250        Bad        100   
25  25  34.0  60000.0         0    Delhi  200-250        Bad        100   
26  26  20.0  30000.0         0  Chennai  250-300       Good        100   
27  27  15.0  30000.0         3    Delhi  250-300       Good        100   
28  28   7.0      NaN         3   Mumbai  100-150       Good        100   
29  29  12.0  60000.0         1   Mumbai  150-200   Pathetic        100   
30  30  45.0  30000.0         4  Chennai  150-200       Good        100   
31  31  12.0  30000.0         2    Delhi  150-200  Excellent        100   
32  32  12.0  10000.0         4    Delhi  100-150  Excellent        100   
33  33  20.0  40000.0         2  Chennai  150-200  Excellent        100   
34  34  20.0      NaN         1  Kolkata  200-250  Excellent        100   
35  35   7.0  10000.0         3  Kolkata  200-250        Bad        100   
36  36  10.0  50000.0         2   Mumbai  150-200  Excellent        100   
37  37   7.0      NaN         3   Mumbai  200-250       Good        100   
38  38   7.0  60000.0         2   Mumbai  100-150   Pathetic        100   
39  39  34.0  50000.0         0   Mumbai  200-250        Bad        100   
40  40  15.0  10000.0         1    Delhi  100-150        Bad        100   
41  41   7.0      NaN         0  Chennai  150-200   Pathetic        100   
42  42  15.0      NaN         4  Kolkata  100-150   Pathetic        100   
43  43  20.0      NaN         0    Delhi  150-200        Bad        100   
44  44  10.0  20000.0         3   Mumbai  250-300   Pathetic        100   
45  45  20.0  20000.0         2   Mumbai  250-300        Bad        100   
46  46  20.0  10000.0         4  Chennai  100-150  Excellent        100   
47  47  15.0  10000.0         2   Mumbai  200-250  Excellent        100   
48  48  34.0  40000.0         4  Kolkata  100-150  Excellent        100   
49  49  20.0  20000.0         4   Mumbai  200-250        Bad        100   

    balance_log  age_children_ratio  
0     11.002100                 NaN  
1     11.002100           34.000000  
2     11.002100                 inf  
3           NaN           

You can do many complex algebraic calculations as well to create/add new columns to the data . notic that when a missing value is involved in any claculation , the result is also a missing value.

Lets say we did not want to this to happen and wanted to impute missing values before proceeding with creating that ratio variable.

we can use function isnull to identify values which are missing 

In [90]:
mydata['age'].isnull()

0      True
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16     True
17    False
18    False
19     True
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
Name: age, dtype: bool

This gives you a logical array which you can use to isolate missing values and then change them to whatever value you want ti impute with

to quickly count howmany missing values are there , you can add sum on top of previous command

In [91]:
mydata['age'].isnull().sum()

4

Lets impute these values with mean 

In [92]:
mydata.loc[mydata['age'].isnull(),'age']=mydata['age'].mean()
mydata['age_children_ratio']=mydata['age']/mydata['children']

In [93]:
mydata

ID        age  balance  children     city     fico     rating  const_var  \
0    0  19.630435  60000.0         0    Delhi  200-250  Excellent        100   
1    1  34.000000  60000.0         1  Kolkata  150-200        Bad        100   
2    2  30.000000  60000.0         0   Mumbai  100-150       Good        100   
3    3  15.000000      NaN         3  Chennai  250-300       Good        100   
4    4  45.000000      NaN         4   Mumbai  100-150       Good        100   
5    5   7.000000  60000.0         3  Kolkata  250-300        Bad        100   
6    6  45.000000  60000.0         0  Chennai  250-300  Excellent        100   
7    7  19.630435  20000.0         3    Delhi  100-150   Pathetic        100   
8    8  10.000000  50000.0         0  Chennai  100-150   Pathetic        100   
9    9  15.000000  40000.0         3    Delhi  100-150  Excellent        100   
10  10  12.000000  60000.0         2   Mumbai  250-300       Good        100   
11  11  30.000000  50000.0         3   Mumbai  100-150       Good        100   
12  12  15.000000  50000.0         3  Kolkata  150-200       Good        100   
13  13  12.000000  30000.0         1    Delhi  150-200  Excellent        100   
14  14  45.000000  50000.0         4  Kolkata  100-150   Pathetic        100   
15  15  34.000000  40000.0         3   Mumbai  250-300       Good        100   
16  16  19.630435  40000.0         0   Mumbai  150-200   Pathetic        100   
17  17  34.000000  40000.0         1  Kolkata  150-200   Pathetic        100   
18  18  15.000000  40000.0         4  Chennai  200-250  Excellent        100   
19  19  19.630435  40000.0         1  Chennai  100-150   Pathetic        100   
20  20   7.000000      NaN         1    Delhi  100-150   Pathetic        100   
21  21  20.000000  50000.0         1   Mumbai  100-150        Bad        100   
22  22  10.000000  10000.0         4    Delhi  200-250       Good        100   
23  23  15.000000  60000.0         2  Kolkata  100-150  Excellent        100   
24  24  15.000000  20000.0         0  Kolkata  200-250        Bad        100   
25  25  34.000000  60000.0         0    Delhi  200-250        Bad        100   
26  26  20.000000  30000.0         0  Chennai  250-300       Good        100   
27  27  15.000000  30000.0         3    Delhi  250-300       Good        100   
28  28   7.000000      NaN         3   Mumbai  100-150       Good        100   
29  29  12.000000  60000.0         1   Mumbai  150-200   Pathetic        100   
30  30  45.000000  30000.0         4  Chennai  150-200       Good        100   
31  31  12.000000  30000.0         2    Delhi  150-200  Excellent        100   
32  32  12.000000  10000.0         4    Delhi  100-150  Excellent        100   
33  33  20.000000  40000.0         2  Chennai  150-200  Excellent        100   
34  34  20.000000      NaN         1  Kolkata  200-250  Excellent        100   
35  35   7.000000  10000.0         3  Kolkata  200-250        Bad        100   
36  36  10.000000  50000.0         2   Mumbai  150-200  Excellent        100   
37  37   7.000000      NaN         3   Mumbai  200-250       Good        100   
38  38   7.000000  60000.0         2   Mumbai  100-150   Pathetic        100   
39  39  34.000000  50000.0         0   Mumbai  200-250        Bad        100   
40  40  15.000000  10000.0         1    Delhi  100-150        Bad        100   
41  41   7.000000      NaN         0  Chennai  150-200   Pathetic        100   
42  42  15.000000      NaN         4  Kolkata  100-150   Pathetic        100   
43  43  20.000000      NaN         0    Delhi  150-200        Bad        100   
44  44  10.000000  20000.0         3   Mumbai  250-300   Pathetic        100   
45  45  20.000000  20000.0         2   Mumbai  250-300        Bad        100   
46  46  20.000000  10000.0         4  Chennai  100-150  Excellent        100   
47  47  15.000000  10000.0         2   Mumbai  200-250  Excellent        100   
48  48  34.000000  40000.0         4  Kolkata  100-150  Excellent        100   
49  

Since age doesnt have missing values anymore , you dont see any missing values in the ratio column , however you do see Inf , which is short for infinity which occurs wherever you are dividing by 0

Next we'll see how to add var based on some condition. Lets say we want to replace the ratings with some numeric score like this , {'pathetic' : -1 , 'bad' : 0 , 'good or excellent': 1 } . we can do it like this 

In [94]:
mydata['rating_score']=np.where(mydata['rating'].isin(['Good','Excellent']),1,0)

In [95]:
mydata.loc[mydata['rating']=='Pathetic','rating_score']=-1

In [96]:
mydata

ID        age  balance  children     city     fico     rating  const_var  \
0    0  19.630435  60000.0         0    Delhi  200-250  Excellent        100   
1    1  34.000000  60000.0         1  Kolkata  150-200        Bad        100   
2    2  30.000000  60000.0         0   Mumbai  100-150       Good        100   
3    3  15.000000      NaN         3  Chennai  250-300       Good        100   
4    4  45.000000      NaN         4   Mumbai  100-150       Good        100   
5    5   7.000000  60000.0         3  Kolkata  250-300        Bad        100   
6    6  45.000000  60000.0         0  Chennai  250-300  Excellent        100   
7    7  19.630435  20000.0         3    Delhi  100-150   Pathetic        100   
8    8  10.000000  50000.0         0  Chennai  100-150   Pathetic        100   
9    9  15.000000  40000.0         3    Delhi  100-150  Excellent        100   
10  10  12.000000  60000.0         2   Mumbai  250-300       Good        100   
11  11  30.000000  50000.0         3   Mumbai  100-150       Good        100   
12  12  15.000000  50000.0         3  Kolkata  150-200       Good        100   
13  13  12.000000  30000.0         1    Delhi  150-200  Excellent        100   
14  14  45.000000  50000.0         4  Kolkata  100-150   Pathetic        100   
15  15  34.000000  40000.0         3   Mumbai  250-300       Good        100   
16  16  19.630435  40000.0         0   Mumbai  150-200   Pathetic        100   
17  17  34.000000  40000.0         1  Kolkata  150-200   Pathetic        100   
18  18  15.000000  40000.0         4  Chennai  200-250  Excellent        100   
19  19  19.630435  40000.0         1  Chennai  100-150   Pathetic        100   
20  20   7.000000      NaN         1    Delhi  100-150   Pathetic        100   
21  21  20.000000  50000.0         1   Mumbai  100-150        Bad        100   
22  22  10.000000  10000.0         4    Delhi  200-250       Good        100   
23  23  15.000000  60000.0         2  Kolkata  100-150  Excellent        100   
24  24  15.000000  20000.0         0  Kolkata  200-250        Bad        100   
25  25  34.000000  60000.0         0    Delhi  200-250        Bad        100   
26  26  20.000000  30000.0         0  Chennai  250-300       Good        100   
27  27  15.000000  30000.0         3    Delhi  250-300       Good        100   
28  28   7.000000      NaN         3   Mumbai  100-150       Good        100   
29  29  12.000000  60000.0         1   Mumbai  150-200   Pathetic        100   
30  30  45.000000  30000.0         4  Chennai  150-200       Good        100   
31  31  12.000000  30000.0         2    Delhi  150-200  Excellent        100   
32  32  12.000000  10000.0         4    Delhi  100-150  Excellent        100   
33  33  20.000000  40000.0         2  Chennai  150-200  Excellent        100   
34  34  20.000000      NaN         1  Kolkata  200-250  Excellent        100   
35  35   7.000000  10000.0         3  Kolkata  200-250        Bad        100   
36  36  10.000000  50000.0         2   Mumbai  150-200  Excellent        100   
37  37   7.000000      NaN         3   Mumbai  200-250       Good        100   
38  38   7.000000  60000.0         2   Mumbai  100-150   Pathetic        100   
39  39  34.000000  50000.0         0   Mumbai  200-250        Bad        100   
40  40  15.000000  10000.0         1    Delhi  100-150        Bad        100   
41  41   7.000000      NaN         0  Chennai  150-200   Pathetic        100   
42  42  15.000000      NaN         4  Kolkata  100-150   Pathetic        100   
43  43  20.000000      NaN         0    Delhi  150-200        Bad        100   
44  44  10.000000  20000.0         3   Mumbai  250-300   Pathetic        100   
45  45  20.000000  20000.0         2   Mumbai  250-300        Bad        100   
46  46  20.000000  10000.0         4  Chennai  100-150  Excellent        100   
47  47  15.000000  10000.0         2   Mumbai  200-250  Excellent        100   
48  48  34.000000  40000.0         4  Kolkata  100-150  Excellent        100   
49  

ofcourse there are many other ways to do the same , i just wanted to introduce you to np.where function which works just like ifelse functions you must have seen in other languages

In [97]:
mydata.head()

ID        age  balance  children     city     fico     rating  const_var  \
0   0  19.630435  60000.0         0    Delhi  200-250  Excellent        100   
1   1  34.000000  60000.0         1  Kolkata  150-200        Bad        100   
2   2  30.000000  60000.0         0   Mumbai  100-150       Good        100   
3   3  15.000000      NaN         3  Chennai  250-300       Good        100   
4   4  45.000000      NaN         4   Mumbai  100-150       Good        100   

   balance_log  age_children_ratio  rating_score  
0      11.0021                 inf             1  
1      11.0021           34.000000             0  
2      11.0021                 inf             1  
3          NaN            5.000000             1  
4          NaN           11.250000             1

many at times we get columns which can be separated into many columns , its a dificult problem to solve if you start writing a for loop to process each value etc . Its far more easier to solve however and is a very useful thing to know while doing data prep 

we will take this step by step , your first instinct will be to apply split function to the column directly because its a character column. There is a slight difference however , these columns are stored as object type and they dont understand string functions , what we'll need to do is this , this stays true for all string functions , not just split 

In [98]:
mydata['fico'].split("-")

AttributeError: 'Series' object has no attribute 'split'

In [99]:
mydata['fico'].str.split("-")

0     [200, 250]
1     [150, 200]
2     [100, 150]
3     [250, 300]
4     [100, 150]
5     [250, 300]
6     [250, 300]
7     [100, 150]
8     [100, 150]
9     [100, 150]
10    [250, 300]
11    [100, 150]
12    [150, 200]
13    [150, 200]
14    [100, 150]
15    [250, 300]
16    [150, 200]
17    [150, 200]
18    [200, 250]
19    [100, 150]
20    [100, 150]
21    [100, 150]
22    [200, 250]
23    [100, 150]
24    [200, 250]
25    [200, 250]
26    [250, 300]
27    [250, 300]
28    [100, 150]
29    [150, 200]
30    [150, 200]
31    [150, 200]
32    [100, 150]
33    [150, 200]
34    [200, 250]
35    [200, 250]
36    [150, 200]
37    [200, 250]
38    [100, 150]
39    [200, 250]
40    [100, 150]
41    [150, 200]
42    [100, 150]
43    [150, 200]
44    [250, 300]
45    [250, 300]
46    [100, 150]
47    [200, 250]
48    [100, 150]
49    [200, 250]
Name: fico, dtype: object

this is not enough , we'd rather want these into two separate columns , which can be achieved by using option exapnd

In [100]:
mydata['fico'].str.split("-",expand=True)

0    1
0   200  250
1   150  200
2   100  150
3   250  300
4   100  150
5   250  300
6   250  300
7   100  150
8   100  150
9   100  150
10  250  300
11  100  150
12  150  200
13  150  200
14  100  150
15  250  300
16  150  200
17  150  200
18  200  250
19  100  150
20  100  150
21  100  150
22  200  250
23  100  150
24  200  250
25  200  250
26  250  300
27  250  300
28  100  150
29  150  200
30  150  200
31  150  200
32  100  150
33  150  200
34  200  250
35  200  250
36  150  200
37  200  250
38  100  150
39  200  250
40  100  150
41  150  200
42  100  150
43  150  200
44  250  300
45  250  300
46  100  150
47  200  250
48  100  150
49  200  250

this be default creates a data frame , you can either concatenate this after giving proper header or directly assing to new columns in your data like this 

In [101]:
k=mydata['fico'].str.split("-",expand=True).astype(float)
mydata['f1'],mydata['f2']=k[0],k[1]

In [102]:
del mydata['fico']

we also converted them to numeric type as needed simultaneously , dont think that its a required step

In [103]:
mydata

ID        age  balance  children     city     rating  const_var  \
0    0  19.630435  60000.0         0    Delhi  Excellent        100   
1    1  34.000000  60000.0         1  Kolkata        Bad        100   
2    2  30.000000  60000.0         0   Mumbai       Good        100   
3    3  15.000000      NaN         3  Chennai       Good        100   
4    4  45.000000      NaN         4   Mumbai       Good        100   
5    5   7.000000  60000.0         3  Kolkata        Bad        100   
6    6  45.000000  60000.0         0  Chennai  Excellent        100   
7    7  19.630435  20000.0         3    Delhi   Pathetic        100   
8    8  10.000000  50000.0         0  Chennai   Pathetic        100   
9    9  15.000000  40000.0         3    Delhi  Excellent        100   
10  10  12.000000  60000.0         2   Mumbai       Good        100   
11  11  30.000000  50000.0         3   Mumbai       Good        100   
12  12  15.000000  50000.0         3  Kolkata       Good        100   
13  13  12.000000  30000.0         1    Delhi  Excellent        100   
14  14  45.000000  50000.0         4  Kolkata   Pathetic        100   
15  15  34.000000  40000.0         3   Mumbai       Good        100   
16  16  19.630435  40000.0         0   Mumbai   Pathetic        100   
17  17  34.000000  40000.0         1  Kolkata   Pathetic        100   
18  18  15.000000  40000.0         4  Chennai  Excellent        100   
19  19  19.630435  40000.0         1  Chennai   Pathetic        100   
20  20   7.000000      NaN         1    Delhi   Pathetic        100   
21  21  20.000000  50000.0         1   Mumbai        Bad        100   
22  22  10.000000  10000.0         4    Delhi       Good        100   
23  23  15.000000  60000.0         2  Kolkata  Excellent        100   
24  24  15.000000  20000.0         0  Kolkata        Bad        100   
25  25  34.000000  60000.0         0    Delhi        Bad        100   
26  26  20.000000  30000.0         0  Chennai       Good        100   
27  27  15.000000  30000.0         3    Delhi       Good        100   
28  28   7.000000      NaN         3   Mumbai       Good        100   
29  29  12.000000  60000.0         1   Mumbai   Pathetic        100   
30  30  45.000000  30000.0         4  Chennai       Good        100   
31  31  12.000000  30000.0         2    Delhi  Excellent        100   
32  32  12.000000  10000.0         4    Delhi  Excellent        100   
33  33  20.000000  40000.0         2  Chennai  Excellent        100   
34  34  20.000000      NaN         1  Kolkata  Excellent        100   
35  35   7.000000  10000.0         3  Kolkata        Bad        100   
36  36  10.000000  50000.0         2   Mumbai  Excellent        100   
37  37   7.000000      NaN         3   Mumbai       Good        100   
38  38   7.000000  60000.0         2   Mumbai   Pathetic        100   
39  39  34.000000  50000.0         0   Mumbai        Bad        100   
40  40  15.000000  10000.0         1    Delhi        Bad        100   
41  41   7.000000      NaN         0  Chennai   Pathetic        100   
42  42  15.000000      NaN         4  Kolkata   Pathetic        100   
43  43  20.000000      NaN         0    Delhi        Bad        100   
44  44  10.000000  20000.0         3   Mumbai   Pathetic        100   
45  45  20.000000  20000.0         2   Mumbai        Bad        100   
46  46  20.000000  10000.0         4  Chennai  Excellent        100   
47  47  15.000000  10000.0         2   Mumbai  Excellent        100   
48  48  34.000000  40000.0         4  Kolkata  Excellent        100   
49  49  20.000000  20000.0         4   Mumbai        Bad        100   

    balance_log  age_children_ratio  rating_score     f1     f2  
0     11.002100                 inf             1  200.0  250.0  
1     11.002100           34.000000             0  150.0  200.0  
2     11.002100                 inf             1  100.0  150.0  
3           NaN            5.000000             1  250.0  300.0  
4           NaN           11.250000             1  1

For all the machine algorithm that you will encounter , you will need to convert categorical variables to flag variables . If a variable has n distinct categories , you need to create n-1 flag variables . you can do that manually like this 

In [104]:
mydata['city_mumbai']=np.where(mydata['city']=='Mumbai',1,0)

In [105]:
mydata['city_chennai']=(mydata['city']=='Chennai').astype(int)

for creating flag vars you can use either of the methods , end result is same . We need to create one more flag variable

In [106]:
mydata['city_kolkata']=np.where(mydata['city']=='Kolkata',1,0)

once the flag variable has been created , we dont need the original variables 

In [107]:
del mydata['city']

this is all fine but requires a lot of coding even if we somehow manage to put inside a for loop , however we dont really need to go through all this trouble . We can use get_dummies function from pandas directly to do this 

In [108]:
dummy=pd.get_dummies(mydata['rating'],drop_first=True,prefix='rating')

In [109]:
dummy

rating_Excellent  rating_Good  rating_Pathetic
0                  1            0                0
1                  0            0                0
2                  0            1                0
3                  0            1                0
4                  0            1                0
5                  0            0                0
6                  1            0                0
7                  0            0                1
8                  0            0                1
9                  1            0                0
10                 0            1                0
11                 0            1                0
12                 0            1                0
13                 1            0                0
14                 0            0                1
15                 0            1                0
16                 0            0                1
17                 0            0                1
18                 1            0                0
19                 0            0                1
20                 0            0                1
21                 0            0                0
22                 0            1                0
23                 1            0                0
24                 0            0                0
25                 0            0                0
26                 0            1                0
27                 0            1                0
28                 0            1                0
29                 0            0                1
30                 0            1                0
31                 1            0                0
32                 1            0                0
33                 1            0                0
34                 1            0                0
35                 0            0                0
36                 1            0                0
37                 0            1                0
38                 0            0                1
39                 0            0                0
40                 0            0                0
41                 0            0                1
42                 0            0                1
43                 0            0                0
44                 0            0                1
45                 0            0                0
46                 1            0                0
47                 1            0                0
48                 1            0                0
49                 0            0                0

we can now simply attach it back to the data using pd.concat

In [110]:
mydata=pd.concat([mydata,dummy],axis=1)

In [111]:
del mydata['rating']

In [112]:
mydata

ID        age  balance  children  const_var  balance_log  \
0    0  19.630435  60000.0         0        100    11.002100   
1    1  34.000000  60000.0         1        100    11.002100   
2    2  30.000000  60000.0         0        100    11.002100   
3    3  15.000000      NaN         3        100          NaN   
4    4  45.000000      NaN         4        100          NaN   
5    5   7.000000  60000.0         3        100    11.002100   
6    6  45.000000  60000.0         0        100    11.002100   
7    7  19.630435  20000.0         3        100     9.903488   
8    8  10.000000  50000.0         0        100    10.819778   
9    9  15.000000  40000.0         3        100    10.596635   
10  10  12.000000  60000.0         2        100    11.002100   
11  11  30.000000  50000.0         3        100    10.819778   
12  12  15.000000  50000.0         3        100    10.819778   
13  13  12.000000  30000.0         1        100    10.308953   
14  14  45.000000  50000.0         4        100    10.819778   
15  15  34.000000  40000.0         3        100    10.596635   
16  16  19.630435  40000.0         0        100    10.596635   
17  17  34.000000  40000.0         1        100    10.596635   
18  18  15.000000  40000.0         4        100    10.596635   
19  19  19.630435  40000.0         1        100    10.596635   
20  20   7.000000      NaN         1        100          NaN   
21  21  20.000000  50000.0         1        100    10.819778   
22  22  10.000000  10000.0         4        100     9.210340   
23  23  15.000000  60000.0         2        100    11.002100   
24  24  15.000000  20000.0         0        100     9.903488   
25  25  34.000000  60000.0         0        100    11.002100   
26  26  20.000000  30000.0         0        100    10.308953   
27  27  15.000000  30000.0         3        100    10.308953   
28  28   7.000000      NaN         3        100          NaN   
29  29  12.000000  60000.0         1        100    11.002100   
30  30  45.000000  30000.0         4        100    10.308953   
31  31  12.000000  30000.0         2        100    10.308953   
32  32  12.000000  10000.0         4        100     9.210340   
33  33  20.000000  40000.0         2        100    10.596635   
34  34  20.000000      NaN         1        100          NaN   
35  35   7.000000  10000.0         3        100     9.210340   
36  36  10.000000  50000.0         2        100    10.819778   
37  37   7.000000      NaN         3        100          NaN   
38  38   7.000000  60000.0         2        100    11.002100   
39  39  34.000000  50000.0         0        100    10.819778   
40  40  15.000000  10000.0         1        100     9.210340   
41  41   7.000000      NaN         0        100          NaN   
42  42  15.000000      NaN         4        100          NaN   
43  43  20.000000      NaN         0        100          NaN   
44  44  10.000000  20000.0         3        100     9.903488   
45  45  20.000000  20000.0         2        100     9.903488   
46  46  20.000000  10000.0         4        100     9.210340   
47  47  15.000000  10000.0         2        100     9.210340   
48  48  34.000000  40000.0         4        100    10.596635   
49  49  20.000000  20000.0         4        100     9.903488   

    age_children_ratio  rating_score     f1     f2  city_mumbai  city_chennai  \
0                  inf             1  200.0  250.0            0             0   
1            34.000000             0  150.0  200.0            0             0   
2                  inf             1  100.0  150.0            1             0   
3             5.000000             1  250.0  300.0            0             1   
4            11.250000             1  100.0  150.0            1             0   
5             2.333333             0  250.0  300.0            0             0   
6                  inf             1  250.0  300.0            0             1   
7             6.543478            -1  100.0  150.0            0             0   
8         

we'll stop our discussion here , keep in mind that we will not be doing all of what we learned here at once for any one dataset . multiple techniues some at a time will be useful while preparing data for machine learning algos. In the next section we'll see how to sort dataframes and combine multiple dataset in various ways. 

# Sorting , Merging Dataframes

hey everyone this is lalit here again , we'll continue with our discussion on dataframes in this sections as well . We will talk about 

1. sorting data by one or more column in ascending or descending manner 
2. combining dataframse vertically or horizontally
3. Merging them using keys , left, right , inner and outer join

Lets simulate data quickly for sorting 

In [113]:
import pandas as pd
import numpy as np

In [114]:
df = pd.DataFrame(np.random.randint(2, 8,(20,4)), columns=list('ABCD'))

In [115]:
df

A  B  C  D
0   7  5  7  3
1   3  5  2  2
2   4  3  4  2
3   2  7  4  6
4   2  5  6  4
5   4  3  7  3
6   6  6  5  3
7   3  2  5  7
8   5  5  5  5
9   4  6  4  2
10  2  7  2  5
11  5  5  3  4
12  7  6  4  2
13  4  7  2  4
14  5  6  7  2
15  4  3  2  5
16  7  6  2  4
17  6  6  2  4
18  2  5  4  7
19  3  7  6  7

 Lets sort this by column A 

In [116]:
df.sort_values('A',inplace=True)

In [117]:
df

A  B  C  D
3   2  7  4  6
4   2  5  6  4
10  2  7  2  5
18  2  5  4  7
19  3  7  6  7
1   3  5  2  2
7   3  2  5  7
15  4  3  2  5
13  4  7  2  4
9   4  6  4  2
5   4  3  7  3
2   4  3  4  2
11  5  5  3  4
14  5  6  7  2
8   5  5  5  5
6   6  6  5  3
17  6  6  2  4
12  7  6  4  2
16  7  6  2  4
0   7  5  7  3

for sorting in descending manner we need to use option ascending to False

In [118]:
df.sort_values('A',ascending=False,inplace=True)

In [119]:
df

A  B  C  D
0   7  5  7  3
16  7  6  2  4
12  7  6  4  2
17  6  6  2  4
6   6  6  5  3
8   5  5  5  5
14  5  6  7  2
11  5  5  3  4
2   4  3  4  2
5   4  3  7  3
9   4  6  4  2
13  4  7  2  4
15  4  3  2  5
7   3  2  5  7
1   3  5  2  2
19  3  7  6  7
4   2  5  6  4
18  2  5  4  7
10  2  7  2  5
3   2  7  4  6

we can sort by multiple columns also , sorting by next column in the sequence happens with in the groups formed as results for sorting by previous columns 

In [120]:
df.sort_values(['B','C'],ascending=[True,False])

A  B  C  D
7   3  2  5  7
5   4  3  7  3
2   4  3  4  2
15  4  3  2  5
0   7  5  7  3
4   2  5  6  4
8   5  5  5  5
18  2  5  4  7
11  5  5  3  4
1   3  5  2  2
14  5  6  7  2
6   6  6  5  3
12  7  6  4  2
9   4  6  4  2
16  7  6  2  4
17  6  6  2  4
19  3  7  6  7
3   2  7  4  6
13  4  7  2  4
10  2  7  2  5

this sorts the data by column B in ascending order but , sorting by column C happens in descending manner . Although we havent taken an explicit example for character data, in case of characater data, sorting happens in dictionary order 

Next we'll look at combining datasets by simply stacking them 

In [121]:
df1 = pd.DataFrame([['a', 1], ['b', 2]],columns=['letter', 'number'])
df2 = pd.DataFrame([['c', 3, 'cat'], ['d', 4, 'dog']],columns=['letter', 'number', 'animal'])

In [122]:
df1

letter  number
0      a       1
1      b       2

In [123]:
df2

letter  number animal
0      c       3    cat
1      d       4    dog

lets combine them vertically 

In [124]:
pd.concat([df1,df2],axis=0)

animal letter  number
0    NaN      a       1
1    NaN      b       2
0    cat      c       3
1    dog      d       4

Columns with same name are stacked others end up having missing values for the obs for one of the dataset

if you notice the index , thats also stacked , to reset while stacking itself , you can use option ignore index 

In [125]:
pd.concat([df1,df2],axis=0,ignore_index=True)

animal letter  number
0    NaN      a       1
1    NaN      b       2
2    cat      c       3
3    dog      d       4

In [126]:
df3 = pd.DataFrame([['bird', 'polly'], ['monkey', 'george'],['tiger','john']],columns=['animal', 'name'])

In [127]:
df3

animal    name
0    bird   polly
1  monkey  george
2   tiger    john

In [128]:
pd.concat([df1,df3],axis=1)

letter  number  animal    name
0      a     1.0    bird   polly
1      b     2.0  monkey  george
2    NaN     NaN   tiger    john

if any dataframe as lesser number of rows , those obs end up being assinged missing values 

Many times our datasets need to be combined by keys instead of simply stacking them vertically or horizontally 

In [129]:
df1=pd.DataFrame({"custid":[1,2,3,4,5],
                 "product":["Radio","Radio","Fridge","Fridge","Phone"]})
df2=pd.DataFrame({"custid":[3,4,5,6,7],
                 "state":["UP","UP","UP","MH","MH"]})

we can use function merge for getting different kind of join, key here between two columns is custid 

In [130]:
pd.merge(df1,df2,on=['custid'],how='inner')

custid product state
0       3  Fridge    UP
1       4  Fridge    UP
2       5   Phone    UP

In [131]:
pd.merge(df1,df2,on=['custid'],how='outer')

custid product state
0       1   Radio   NaN
1       2   Radio   NaN
2       3  Fridge    UP
3       4  Fridge    UP
4       5   Phone    UP
5       6     NaN    MH
6       7     NaN    MH

In [132]:
pd.merge(df1,df2,on=['custid'],how='left')

custid product state
0       1   Radio   NaN
1       2   Radio   NaN
2       3  Fridge    UP
3       4  Fridge    UP
4       5   Phone    UP

In [133]:
pd.merge(df1,df2,on=['custid'],how='right')

custid product state
0       3  Fridge    UP
1       4  Fridge    UP
2       5   Phone    UP
3       6     NaN    MH
4       7     NaN    MH